import csv
import json
import os

CSV_FILE = 'dataset.csv'
OUTPUT_FILE = 'backend/src/data/knowledgeBase.js'

print("🔄 Starting Data Ingestion Pipeline...")
print(f"📂 Reading raw dataset from {CSV_FILE}...")

chunks = []
with open(CSV_FILE, mode='r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        # Convert pipe-separated keywords into list
        keywords = row['similarity_keywords'].split('|')
        
        chunk = {
            "id": row['id'],
            "library": row['library'],
            "library_name": row['library_name'],
            "title": row['title'],
            "source_url": row['source_url'],
            "version": row['version'],
            "similarity_keywords": keywords,
            "headline": row['headline'],
            "answer": row['answer'],
            "code_lang": row['code_lang'],
            "code": row['code']
        }
        chunks.append(chunk)

print(f"✅ Extracted {len(chunks)} chunks from CSV.")
print(f"⚙️ Generating Javascript Vector Store Knowledge Base...")

js_content = f"""// AUTO-GENERATED BY PYTHON INGESTION SCRIPT
// Dataset Source: {CSV_FILE}

const config = require('../config');

const VECTOR_STORE = {json.dumps(chunks, indent=2)};

module.exports = {{
  VECTOR_STORE
}};
"""

with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    f.write(js_content)

print(f"🚀 Success! Knowledge Base seeded at {OUTPUT_FILE}")
